# Generated by Django 4.0.6 on 2022-07-31 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'Draft'), (1, 'published')], default=0),
        ),
    ]
